# Generated by Django 4.1.7 on 2023-05-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('vid', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default=None, null=True, upload_to='voter/')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('constituency', models.CharField(max_length=50)),
            ],
        ),
    ]
