# Generated by Django 4.1.7 on 2023-05-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Election', '0001_initial'),
        ('Candidate', '0007_alter_candidate_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.election')),
            ],
        ),
    ]
