# Generated by Django 4.1.7 on 2023-05-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Voter', '0001_initial'),
        ('Election', '0001_initial'),
        ('Candidate', '0007_alter_candidate_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('casted', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate.candidate')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.election')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voter.voter')),
            ],
        ),
    ]
