# Generated by Django 4.1.7 on 2023-04-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='can_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
