# Generated by Django 4.1.7 on 2023-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0002_candidate_can_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='can_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
