# Generated by Django 4.1.7 on 2023-04-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0004_alter_candidate_can_photo_alter_candidate_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='can_photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.ImageField(upload_to='candidate/'),
        ),
    ]
