# Generated by Django 4.1.7 on 2023-05-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0005_alter_candidate_can_photo_alter_candidate_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cid',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
