# Generated by Django 4.1.7 on 2023-05-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0006_remove_candidate_id_candidate_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=50),
        ),
    ]
